### ISSUE TITLE
No support for pom.xml in subdirectory

### ISSUE THREAD

**Issue by mathias-ewald** [olhtbr/maven-cache-resource#2]
My pom.xml is located in data/pom.xml which is unsupported by this resource. The relevant location in the code (I believe) is 

`cd "$git_dir"
[[ -f pom.xml ]] || { echo "There is no pom.xml in the git repo."; exit 1; }`

in "in".

I suggest the addition of a "pom" parameter which is also used in "paths" if no paths is specified and deduce the directory from this parameter.

**Comment by olhtbr** [comment]
Hi @mathias-ewald !

This resource is deprecated and I would suggest using [task caches](https://concourse-ci.org/tasks.html#task-caches) if you are on Concourse 3.3.0+

However, if you can't or don't want to switch to caches, I would gladly add this new feature.

**Comment by olhtbr** [comment]
@mathias-ewald did you manage to solve the issue by upgrading concourse itself?

**Comment by olhtbr** [comment]
I'm closing this, but feel free to reopen.
